global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "api-gestao-vaga"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gestao-vaga:8080"]
        labels:
          application: "api-gestao-vaga"