global:
  scrape_interval: 8s
scrape_configs:
  - job_name: "api-gestao-vaga"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 172.17.0.1:8080
        labels:
          application: "api-gestao-vaga"

          